/* Integration test: anchors through a real Vite dev server.
 *
 * Everything else in the suite calls the injectors directly. This one boots
 * Vite, loads a `vite.config.mjs` written exactly as the reference doc shows,
 * and asks the dev server to transform a real module. That is the only way to
 * catch the failure modes that live in the wiring rather than in the plugin:
 * wrong hook order, `enforce` not applied, the JSX already erased by the time we
 * run, a CommonJS `require` that esbuild turns into a throwing shim when it
 * bundles the config, import analysis rejecting the emitted code.
 *
 * The app is copied to a temporary directory and the config is generated there
 * with the `resolveFrom` path written as a literal. Passing that value through
 * `process.env` instead looks tidier but is unreliable: the config is bundled
 * into a temp module and evaluated in a context where the value does not always
 * survive. A literal removes the variable, and this test is about the plugin.
 *
 * Requires `vite` and `@babel/core`:
 *
 *   SYMBUI_TEST_MODULES=/path/to/node_modules \
 *     node --test tests/vite-integration.test.mjs
 */

import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import test, { after, before } from "node:test";
import { fileURLToPath, pathToFileURL } from "node:url";

const FIXTURE = fileURLToPath(new URL("./fixture/vite-anchor-app", import.meta.url));

/* Optional test-only dependencies are never declared by the skill, so the
 * harness has to be told where they are. Resolution order: an explicit
 * `SYMBUI_TEST_MODULES`, then a normal `npm install` in this repository, then
 * the repository root itself. Never a path from one developer's machine. */
const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));

const CANDIDATES = [
  process.env.SYMBUI_TEST_MODULES,
  path.join(REPO_ROOT, "node_modules"),
  REPO_ROOT,
].filter(Boolean);

function resolveModules() {
  for (const directory of CANDIDATES) {
    try {
      const requireFrom = createRequire(path.join(directory, "noop.js"));
      requireFrom("@babel/core");
      requireFrom.resolve("vite");
      return { directory, requireFrom };
    } catch (error) {
      /* keep looking */
    }
  }
  return null;
}

const found = resolveModules();
const skip = found ? false : "install vite and @babel/core, then set SYMBUI_TEST_MODULES";

const ANCHOR_PATTERN = /data-ui-source["']?\s*[:=]\s*["']([^"']+)["']/g;
const COMPONENT_PATTERN = /data-component["']?\s*[:=]\s*["']([^"']+)["']/g;

let appRoot = null;

/* `require.resolve` lands on Vite's CommonJS entry, and `import()` of a CJS file
 * only reliably populates `default`. Accept either shape.
 */
async function loadVite() {
  const entry = found.requireFrom.resolve("vite");
  const loaded = await import(pathToFileURL(entry).href);
  const vite = typeof loaded.createServer === "function" ? loaded : loaded.default;
  assert.equal(typeof vite.createServer, "function", "could not load the Vite API");
  return vite;
}

before(() => {
  if (!found) return;
  /* `os.tmpdir()` returns `/var/...` on macOS while Vite resolves ids through
   * the real `/private/var/...` path, and the two do not match. Realpath first.
   */
  appRoot = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "symbui-vite-"));
  fs.cpSync(FIXTURE, appRoot, { recursive: true });
  const plugin = path.resolve(fileURLToPath(import.meta.url), "../../annotate-web-ui/plugins/vite-plugin-symbui.mjs");
  fs.writeFileSync(
    path.join(appRoot, "vite.config.mjs"),
    [
      "// Generated by tests/vite-integration.test.mjs — the documented wiring.",
      `import { createSymbuiAnchorPlugin } from ${JSON.stringify(plugin)};`,
      "",
      "export default {",
      "  plugins: [",
      "    createSymbuiAnchorPlugin({",
      `      resolveFrom: ${JSON.stringify(found.directory)},`,
      "      report: false,",
      "    }),",
      "  ],",
      "};",
      "",
    ].join("\n"),
  );
});

after(() => {
  if (appRoot) fs.rmSync(appRoot, { recursive: true, force: true });
});

async function withServer(run) {
  const vite = await loadVite();
  const server = await vite.createServer({
    root: appRoot,
    configFile: path.join(appRoot, "vite.config.mjs"),
    logLevel: "silent",
    server: { middlewareMode: true },
  });
  try {
    return await run(server);
  } finally {
    await server.close();
  }
}

test("vite: a real dev server transforms a component and emits anchors", { skip }, async () => {
  await withServer(async (server) => {
    const result = await server.transformRequest("/src/components/ProductCard.tsx");
    assert.ok(result, "the dev server should have returned a transform result");
    const anchors = [...result.code.matchAll(ANCHOR_PATTERN)].map((match) => match[1]);
    assert.equal(anchors.length, 8, `expected one anchor per host element, got ${anchors.length}`);
    for (const anchor of anchors) {
      assert.match(anchor, /^src\/components\/ProductCard\.tsx:\d+:\d+$/);
    }
    assert.equal(anchors[0], "src/components/ProductCard.tsx:16:4");
    assert.ok(result.code.includes('"data-component": "ProductCard"'), "component name missing");
  });
});

test("vite: the component usage is not annotated, only the element it renders", { skip }, async () => {
  await withServer(async (server) => {
    const result = await server.transformRequest("/src/components/ProductGrid.tsx");
    const anchors = [...result.code.matchAll(ANCHOR_PATTERN)].map((match) => match[1]);
    assert.equal(anchors.length, 1, "only <section> is a host element in this module");
    assert.match(anchors[0], /^src\/components\/ProductGrid\.tsx:5:4$/);
    assert.ok(result.code.includes('"data-component": "ProductGrid"'));
  });
});

test("vite: anchors survive into a module that imports another", { skip }, async () => {
  await withServer(async (server) => {
    const result = await server.transformRequest("/src/App.tsx");
    const anchors = [...result.code.matchAll(ANCHOR_PATTERN)].map((match) => match[1]);
    assert.equal(anchors.length, 3, "<main>, <h1>, and <p>");
    assert.deepEqual(anchors, ["src/App.tsx:9:4", "src/App.tsx:10:6", "src/App.tsx:11:6"]);
    const components = [...result.code.matchAll(COMPONENT_PATTERN)].map((match) => match[1]);
    assert.deepEqual(new Set(components), new Set(["App"]));
  });
});

test("vite: import analysis accepts the emitted code", { skip }, async () => {
  await withServer(async (server) => {
    /* A module whose imports Vite rewrites. If our injected attributes confused
     * the downstream pipeline this is where it would show up.
     */
    const result = await server.transformRequest("/src/App.tsx");
    assert.ok(
      result.code.includes("/src/components/ProductGrid.tsx"),
      "the import should have been rewritten by Vite, not left untouched",
    );
    assert.ok(!result.code.includes("data-ui-source: undefined"), "malformed attribute");
  });
});

test("vite: coverage for a single module is exact", { skip }, async () => {
  await withServer(async (server) => {
    await server.transformRequest("/src/components/ProductCard.tsx");
    const plugin = server.config.plugins.find((entry) => entry.name === "symbui-anchor");
    assert.ok(plugin, "the plugin should be registered under its name");
    const stats = plugin.api.stats();
    /* Exactly one module is asserted on purpose. Asking for two makes the count
     * depend on Vite's import warming, which transforms imported modules as a
     * side effect and is not what this test is about.
     */
    assert.equal(stats.files, 1);
    assert.equal(stats.injected, 8);
    assert.deepEqual(stats.skipped, {}, "every host element in this module is annotated");
  });
});

test("vite: a component usage is counted as a skip, not as an anchor", { skip }, async () => {
  await withServer(async (server) => {
    await server.transformRequest("/src/components/ProductGrid.tsx");
    const plugin = server.config.plugins.find((entry) => entry.name === "symbui-anchor");
    const stats = plugin.api.stats();
    assert.equal(stats.injected, 1, "only the <section> is a host element");
    assert.equal(stats.skipped["component-element"], 1, "the <ProductCard> usage is skipped");
  });
});

test("vite: a production build does not carry anchors", { skip }, async () => {
  const vite = await loadVite();
  const built = await vite.build({
    root: appRoot,
    configFile: path.join(appRoot, "vite.config.mjs"),
    logLevel: "silent",
    write: false,
    build: { minify: false },
  });
  const outputs = Array.isArray(built) ? built : [built];
  const code = outputs
    .flatMap((entry) => entry.output || [])
    .map((chunk) => chunk.code || "")
    .join("\n");
  assert.ok(code.length > 0, "the build should have produced output");
  assert.ok(!code.includes("data-ui-source"), "anchors must not ship to production");
});
